In [2]:
a=[1,2,3,4,5]
print (a)
type (a)

[1, 2, 3, 4, 5]


list

In [18]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import numpy as np
x=np.array(a)
x
type (x)

numpy.ndarray

In [38]:
a=np.array ([[1,2,3],[4,5,6]]) #3D 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a.shape #shpae of list

(2, 3)

In [48]:
a.size #calculate the size

6

In [47]:
a.ndim #how many ope or closebracket in list 

2

In [67]:
a.T#conver rows into column

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
a=a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
b=np.array([11,12,13,14,15,16])
b=b.reshape (2,3)
b

array([[11, 12, 13],
       [14, 15, 16]])

In [117]:

np.concatenate ((a,b)) #join twom list

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [121]:
np.hstack((a,b))#we match column

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [122]:
np.vstack((a,b))#we matching columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [125]:
c=np.array([21,22,23])      #it save perement change #add value
c
c=np.append(c,[25,26,27])
c

array([21, 22, 23, 25, 26, 27])

In [150]:
c=np.insert(c,3,24)#adding element 
c

array([21, 22, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 28, 24, 28, 24, 24, 24, 24, 24, 28, 24, 28, 24, 28, 25,
       28, 26, 27])

In [180]:
c=np.delete(c,[5])
c

array([21, 22, 23, 24, 25, 26, 27])

In [182]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [198]:
y=np.arange(2,20,4)# 2 to 20 with diff 4
y

array([ 2,  6, 10, 14, 18])

In [199]:
y=y.reshape(5,1)
y

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [200]:
y[0:3] #lower limit to upper limit minus 1

array([[ 2],
       [ 6],
       [10]])

In [203]:
np.random.rand(4)

array([0.17482056, 0.4728923 , 0.45278199, 0.46544794])

In [204]:
np.random.rand(2,3)

array([[0.11054882, 0.10434358, 0.45740821],
       [0.11834963, 0.315459  , 0.96320469]])

In [207]:
np.random.randn(3,2,3) # 3 matrix with 2 rows and 3 columns    #just adding 'n' after rand it convert into negative vslue

array([[[-0.64900189, -1.67535907, -1.51476464],
        [ 0.3535521 , -0.90645247,  0.55579795]],

       [[ 2.46682976,  1.87259804,  0.25863337],
        [-0.35439512, -2.88939185,  0.00560712]],

       [[ 1.41033497,  0.04528856, -0.36089375],
        [ 0.1310297 , -0.31329542, -0.6454504 ]]])

In [9]:
c

NameError: name 'c' is not defined