In [4]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [56]:
import pandas as pd
import numpy as np

fruits = np.array(['apple', 'banana', 'cherry'])
prices = np.array([100, 200, 300])

print(fruits)
print(prices)
fruits_series=pd.Series(fruits)
print(fruits_series)
print(type(fruits_series))
print(fruits_series[1])
prices_series=pd.Series(prices)
print(prices_series)
print(prices_series[0])




Fp_dict={
    'Fruit':fruits,
    'Prices':prices
}
df_Fp=pd.DataFrame(Fp_dict)
print(df_Fp)


['apple' 'banana' 'cherry']
[100 200 300]
0     apple
1    banana
2    cherry
dtype: object
<class 'pandas.core.series.Series'>
banana
0    100
1    200
2    300
dtype: int64
100
    Fruit  Prices
0   apple     100
1  banana     200
2  cherry     300


In [60]:
df_Fp.loc[[0],["Fruit","Prices"]]

Fruit  Prices
0  apple     100

In [30]:
import pandas as pd
import numpy as np

student_names = np.array(['Sankalp', 'Sangam', 'Vivek','Samyak','Rushi'])
roll_numbers = np.array([1, 2, 3,4,5])
marks = np.array([80,75,85, 90, 95])
fees_paid = np.array([2000,4000,9000,6000,75000])
courses = np.array(['DS', 'DA', 'BA','JAVA','C++'])

print(student_names)
print(roll_numbers)
print(marks)
print(fees_paid)
print(courses)

names_series = pd.Series(student_names)
roll_numbers_series = pd.Series(roll_numbers)
marks_series = pd.Series(marks)
fees_series = pd.Series(fees_paid)
courses_series = pd.Series(courses)

print(names_series)
print(roll_numbers_series)
print(marks_series)
print(fees_series)
print(courses_series)

students_dict = {
    'Student Name': student_names,
    'Roll Number': roll_numbers,
    'Marks': marks,
    'Courses' : courses,
    'Fees': fees_paid
}
df_students = pd.DataFrame(students_dict)
print(df_students)

['Sankalp' 'Sangam' 'Vivek' 'Samyak' 'Rushi']
[1 2 3 4 5]
[80 75 85 90 95]
[ 2000  4000  9000  6000 75000]
['DS' 'DA' 'BA' 'JAVA' 'C++']
0    Sankalp
1     Sangam
2      Vivek
3     Samyak
4      Rushi
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    80
1    75
2    85
3    90
4    95
dtype: int64
0     2000
1     4000
2     9000
3     6000
4    75000
dtype: int64
0      DS
1      DA
2      BA
3    JAVA
4     C++
dtype: object
  Student Name  Roll Number  Marks Courses   Fees
0      Sankalp            1     80      DS   2000
1       Sangam            2     75      DA   4000
2        Vivek            3     85      BA   9000
3       Samyak            4     90    JAVA   6000
4        Rushi            5     95     C++  75000


In [24]:
print(df_students[1:2])

  Student Name  Roll Number  Marks Courses  Fees
1       Sangam            2     75      DA  4000


In [26]:
print (df_students[:5])

  Student Name  Roll Number  Marks Courses   Fees
0      Sankalp            1     80      DS   2000
1       Sangam            2     75      DA   4000
2        Vivek            3     85      BA   9000
3       Samyak            4     90    JAVA   6000
4        Rushi            5     95     C++  75000


In [33]:
print(df_Fp["Fruit"])

0     apple
1    banana
2    cherry
Name: Fruit, dtype: object


In [35]:
print(type(df_Fp[["Fruit"]]))

<class 'pandas.core.frame.DataFrame'>


In [39]:
#accessing rows using labled based 
#iLoc-----accessing rows using index based
df_students.loc[0]

Student Name    Sankalp
Roll Number           1
Marks                80
Courses              DS
Fees               2000
Name: 0, dtype: object

In [49]:
df_students.loc[[0,2,3,4]]

Student Name  Roll Number  Marks Courses   Fees
0      Sankalp            1     80      DS   2000
2        Vivek            3     85      BA   9000
3       Samyak            4     90    JAVA   6000
4        Rushi            5     95     C++  75000

In [53]:
df_students.iloc[[0,4]]

Student Name  Roll Number  Marks Courses   Fees
0      Sankalp            1     80      DS   2000
4        Rushi            5     95     C++  75000

In [61]:
df_students.loc[[0],["Marks","Fees"]]

Marks  Fees
0     80  2000

In [65]:
df_students.loc[0:3,["Student Name","Courses"]]

Student Name Courses
0      Sankalp      DS
1       Sangam      DA
2        Vivek      BA
3       Samyak    JAVA

In [32]:
df_students.iloc[ :,:]

Student Name  Roll Number  Marks Courses   Fees
0      Sankalp            1     80      DS   2000
1       Sangam            2     75      DA   4000
2        Vivek            3     85      BA   9000
3       Samyak            4     90    JAVA   6000
4        Rushi            5     95     C++  75000

In [69]:
df_students.iloc[0,[0,3]]

Student Name    Sankalp
Courses              DS
Name: 0, dtype: object

In [24]:
df_students."info"()

SyntaxError: invalid syntax (1066803619.py, line 1)

In [33]:
df_students['percentage']=df_student['Marks']/200*100
print(df_students)

NameError: name 'df_student' is not defined